# Generated by Django 3.1 on 2021-01-22 21:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainContent', '0002_auto_20210123_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='nothing', max_length=5000),
        ),
    ]
