# Generated by Django 3.1 on 2021-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainContent', '0006_auto_20210304_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='IIT_Guwahati_Logo.svg.png', upload_to='profile_pics'),
        ),
    ]
